version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: apollo
    versions:
    - 2.32.1
    - 2.32.5
    - 2.32.8
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.3
    - 2.13.4
    - 2.14.0
    - 2.14.1
    - 2.14.2
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
